### ISSUE TITLE
Appointment/check-in deletion confirmation.

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#18]
The user wants to see a confirmation message before the appointment or check in gets deleted. The conformation message makes sure that the remove button is not clicked accidentally.

**Comment by karen-lo** [comment]
Added a modal container from lines 268-278 in appointments.html with two buttons "yes" and "no." These buttons are linked to functions in appointment.js lines 35-52. Basically, the yes button sends a DELETE request to our database and removes the modal div while the no button only removes the modal div.
