### ISSUE TITLE
Dashboard Calendar

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#20]
There is a calendar on the dashboard which shows the appointments.

**Comment by j8chou** [comment]
A little background. The calendar was added through the use of a javascript library called [FullCalendar](https://fullcalendar.io/). Rendering is done entirely on the client side through three scripts - fullcalendar.js, moment.js, jquery.js. There is one single web hook that I placed in app.js which queries the db for all appointments within a date range for a specific company and returns it as a json object to the front end.

I want to move the function into appointment-controller.js will look into that later.
