### ISSUE TITLE
Notification when appointment is created.

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#21]

**Comment by karen-lo** [comment]
COMPLETED:
I added a div on line 150 of appointments.html for the notification with the display attribute as none. Then the save button on the form changes the display attribute to the default value. This is implemented on line 69 in appointments.js. I also added an onclick function on line 30-33 of the same file to close the notification. There is some new CSS from line 67-86 in appointment.css.

**Comment by endeavors** [comment]
Unit tests are completed.
