### ISSUE TITLE
Dashboard Pi Chart

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#28]

**Comment by j8chou** [comment]
New functions added/updated to support pi_chart and appointment rehash:

`appointment.controller.js@getToday`: GET Request taking in company_id as parameter; returns a list of appointments for the day and future days

`appointment.controller.js@getAll`: Updated GET Request taking in company_id as parameter; returns a list of appointments for the company in descending order

`appointment.controller.js@updateCancelled`: POST Request taking in json object {"id": appointment_id}; returns updated appointment with status as cancelled

`appointment.controller.js@markNoShow`: Normal function that is ran every five minutes. Goes through and marks appointments that have passed for over five minutes as "no show".

`appointment.controller.js@markNoShow`: GET Request taking in company_id as parameter. Returns a json of [{"status" : "no show", "count": 8}, {"status" : "show", "count": 8}, {"status" : "cancelled", "count": 8}, {"status" : "walk-ins", "count": 8}]

`visitorList.controller.js@create`: Parameters are same as existing functions but functionality was modified to update the status of a matching appointment to show. In addition, if there are no matching appointments it is considered a "walk_in". Therefore, either instantiate a new visitorList or add 1 to the "walk_in" count of an existing visitorList.

**Comment by endeavors** [comment]
done
