### ISSUE TITLE
Remove Gear button and create a logout instead (for all pages)

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#38]

**Comment by i3dly** [comment]
COMPLETE: Currently in branch DevDavid off of branch Dev, as of June 4, 2017.

Gear icon in the top right corner of pages client/assets/native/views/appointments.html, company-dashboard.html, employees.html, form-builder.html, settings.html and visitors.html have been replaced with a standalone logout button.

The new logout button is styled by #logoutButton_side in shared-dashboard.css from client/assets/native/css and neon*.css styles from client/assets/css.

**Comment by i3dly** [comment]
No new functions to be tested.
